
package com.sones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.sones_library_commons.SecurityToken;
import org.datacontract.schemas._2004._07.system.ArrayOfTupleOflonganyType;
import org.datacontract.schemas._2004._07.system.ArrayOfTupleOfstringanyType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EdgeInstanceService", targetNamespace = "http://www.sones.com")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.sones.ObjectFactory.class,
    org.datacontract.schemas._2004._07.sones_library_commons.ObjectFactory.class,
    org.datacontract.schemas._2004._07.system.ObjectFactory.class
})
public interface EdgeInstanceService {


    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myPropertyID
     * @param myGraphElement
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "GetPropertyByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/GetPropertyByEdgeInstance")
    @WebResult(name = "GetPropertyByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetPropertyByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyByEdgeInstance")
    @ResponseWrapper(localName = "GetPropertyByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyByEdgeInstanceResponse")
    public Object getPropertyByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement,
        @WebParam(name = "myPropertyID", targetNamespace = "http://www.sones.com")
        Long myPropertyID);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myPropertyID
     * @param myGraphElement
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasPropertyByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/HasPropertyByEdgeInstance")
    @WebResult(name = "HasPropertyByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasPropertyByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.HasPropertyByEdgeInstance")
    @ResponseWrapper(localName = "HasPropertyByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasPropertyByEdgeInstanceResponse")
    public Boolean hasPropertyByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement,
        @WebParam(name = "myPropertyID", targetNamespace = "http://www.sones.com")
        Long myPropertyID);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myGraphElement
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetCountOfPropertiesByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/GetCountOfPropertiesByEdgeInstance")
    @WebResult(name = "GetCountOfPropertiesByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetCountOfPropertiesByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.GetCountOfPropertiesByEdgeInstance")
    @ResponseWrapper(localName = "GetCountOfPropertiesByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetCountOfPropertiesByEdgeInstanceResponse")
    public Integer getCountOfPropertiesByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myGraphElement
     * @return
     *     returns org.datacontract.schemas._2004._07.system.ArrayOfTupleOflonganyType
     */
    @WebMethod(operationName = "GetAllPropertiesByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/GetAllPropertiesByEdgeInstance")
    @WebResult(name = "GetAllPropertiesByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetAllPropertiesByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllPropertiesByEdgeInstance")
    @ResponseWrapper(localName = "GetAllPropertiesByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllPropertiesByEdgeInstanceResponse")
    public ArrayOfTupleOflonganyType getAllPropertiesByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myPropertyID
     * @param myGraphElement
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPropertyAsStringByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/GetPropertyAsStringByEdgeInstance")
    @WebResult(name = "GetPropertyAsStringByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetPropertyAsStringByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyAsStringByEdgeInstance")
    @ResponseWrapper(localName = "GetPropertyAsStringByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyAsStringByEdgeInstanceResponse")
    public String getPropertyAsStringByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement,
        @WebParam(name = "myPropertyID", targetNamespace = "http://www.sones.com")
        Long myPropertyID);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myPropertyName
     * @param myGraphElement
     * @return
     *     returns java.lang.Object
     */
    @WebMethod(operationName = "GetUnstructuredPropertyByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/GetUnstructuredPropertyByEdgeInstance")
    @WebResult(name = "GetUnstructuredPropertyByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetUnstructuredPropertyByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.GetUnstructuredPropertyByEdgeInstance")
    @ResponseWrapper(localName = "GetUnstructuredPropertyByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetUnstructuredPropertyByEdgeInstanceResponse")
    public Object getUnstructuredPropertyByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement,
        @WebParam(name = "myPropertyName", targetNamespace = "http://www.sones.com")
        String myPropertyName);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myPropertyName
     * @param myGraphElement
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasUnstructuredPropertyByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/HasUnstructuredPropertyByEdgeInstance")
    @WebResult(name = "HasUnstructuredPropertyByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasUnstructuredPropertyByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.HasUnstructuredPropertyByEdgeInstance")
    @ResponseWrapper(localName = "HasUnstructuredPropertyByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasUnstructuredPropertyByEdgeInstanceResponse")
    public Boolean hasUnstructuredPropertyByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement,
        @WebParam(name = "myPropertyName", targetNamespace = "http://www.sones.com")
        String myPropertyName);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myGraphElement
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod(operationName = "GetCountOfUnstructuredPropertiesByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/GetCountOfUnstructuredPropertiesByEdgeInstance")
    @WebResult(name = "GetCountOfUnstructuredPropertiesByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetCountOfUnstructuredPropertiesByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.GetCountOfUnstructuredPropertiesByEdgeInstance")
    @ResponseWrapper(localName = "GetCountOfUnstructuredPropertiesByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetCountOfUnstructuredPropertiesByEdgeInstanceResponse")
    public Integer getCountOfUnstructuredPropertiesByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myGraphElement
     * @return
     *     returns org.datacontract.schemas._2004._07.system.ArrayOfTupleOfstringanyType
     */
    @WebMethod(operationName = "GetAllUnstructuredPropertiesByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/GetAllUnstructuredPropertiesByEdgeInstance")
    @WebResult(name = "GetAllUnstructuredPropertiesByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetAllUnstructuredPropertiesByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllUnstructuredPropertiesByEdgeInstance")
    @ResponseWrapper(localName = "GetAllUnstructuredPropertiesByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllUnstructuredPropertiesByEdgeInstanceResponse")
    public ArrayOfTupleOfstringanyType getAllUnstructuredPropertiesByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myPropertyName
     * @param myGraphElement
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetUnstructuredPropertyAsStringByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/GetUnstructuredPropertyAsStringByEdgeInstance")
    @WebResult(name = "GetUnstructuredPropertyAsStringByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetUnstructuredPropertyAsStringByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.GetUnstructuredPropertyAsStringByEdgeInstance")
    @ResponseWrapper(localName = "GetUnstructuredPropertyAsStringByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetUnstructuredPropertyAsStringByEdgeInstanceResponse")
    public String getUnstructuredPropertyAsStringByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement,
        @WebParam(name = "myPropertyName", targetNamespace = "http://www.sones.com")
        String myPropertyName);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myGraphElement
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CommentByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/CommentByEdgeInstance")
    @WebResult(name = "CommentByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "CommentByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.CommentByEdgeInstance")
    @ResponseWrapper(localName = "CommentByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CommentByEdgeInstanceResponse")
    public String commentByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myGraphElement
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "CreationDateByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/CreationDateByEdgeInstance")
    @WebResult(name = "CreationDateByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "CreationDateByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.CreationDateByEdgeInstance")
    @ResponseWrapper(localName = "CreationDateByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CreationDateByEdgeInstanceResponse")
    public Long creationDateByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myGraphElement
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "ModificationDateByEdgeInstance", action = "http://www.sones.com/EdgeInstanceService/ModificationDateByEdgeInstance")
    @WebResult(name = "ModificationDateByEdgeInstanceResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "ModificationDateByEdgeInstance", targetNamespace = "http://www.sones.com", className = "com.sones.ModificationDateByEdgeInstance")
    @ResponseWrapper(localName = "ModificationDateByEdgeInstanceResponse", targetNamespace = "http://www.sones.com", className = "com.sones.ModificationDateByEdgeInstanceResponse")
    public Long modificationDateByEdgeInstance(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myGraphElement", targetNamespace = "http://www.sones.com")
        ServiceEdgeInstance myGraphElement);

}
