
package com.sones;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOflongstring;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOflong;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GraphDS", targetNamespace = "http://www.sones.com")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.sones.ObjectFactory.class,
    org.datacontract.schemas._2004._07.system.ObjectFactory.class
})
public interface GraphDS {


    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myVertexTypePreDef
     * @return
     *     returns com.sones.ServiceVertexType
     */
    @WebMethod(operationName = "CreateVertexType", action = "http://www.sones.com/GraphDS/CreateVertexType")
    @WebResult(name = "CreateVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "CreateVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.CreateVertexType")
    @ResponseWrapper(localName = "CreateVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CreateVertexTypeResponse")
    public ServiceVertexType createVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexTypePreDef", targetNamespace = "http://www.sones.com")
        ServiceVertexTypePredefinition myVertexTypePreDef);

    /**
     * 
     * @param myTransToken
     * @param myVertexType
     * @param mySecurityToken
     * @param myChangeset
     * @return
     *     returns com.sones.ServiceVertexType
     */
    @WebMethod(operationName = "AlterVertexType", action = "http://www.sones.com/GraphDS/AlterVertexType")
    @WebResult(name = "AlterVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "AlterVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.AlterVertexType")
    @ResponseWrapper(localName = "AlterVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.AlterVertexTypeResponse")
    public ServiceVertexType alterVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType,
        @WebParam(name = "myChangeset", targetNamespace = "http://www.sones.com")
        ServiceAlterVertexChangeset myChangeset);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myEdgeType
     * @param myChangeset
     * @return
     *     returns com.sones.ServiceEdgeType
     */
    @WebMethod(operationName = "AlterEdgeType", action = "http://www.sones.com/GraphDS/AlterEdgeType")
    @WebResult(name = "AlterEdgeTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "AlterEdgeType", targetNamespace = "http://www.sones.com", className = "com.sones.AlterEdgeType")
    @ResponseWrapper(localName = "AlterEdgeTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.AlterEdgeTypeResponse")
    public ServiceEdgeType alterEdgeType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myEdgeType", targetNamespace = "http://www.sones.com")
        ServiceEdgeType myEdgeType,
        @WebParam(name = "myChangeset", targetNamespace = "http://www.sones.com")
        ServiceAlterEdgeChangeset myChangeset);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myVertexTypeName
     * @return
     *     returns com.sones.ServiceVertexType
     */
    @WebMethod(operationName = "GetVertexType", action = "http://www.sones.com/GraphDS/GetVertexType")
    @WebResult(name = "GetVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexType")
    @ResponseWrapper(localName = "GetVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexTypeResponse")
    public ServiceVertexType getVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexTypeName", targetNamespace = "http://www.sones.com")
        String myVertexTypeName);

    /**
     * 
     * @param mySecurityToken
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "BeginTransaction", action = "http://www.sones.com/GraphDS/BeginTransaction")
    @WebResult(name = "BeginTransactionResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "BeginTransaction", targetNamespace = "http://www.sones.com", className = "com.sones.BeginTransaction")
    @ResponseWrapper(localName = "BeginTransactionResponse", targetNamespace = "http://www.sones.com", className = "com.sones.BeginTransactionResponse")
    public Long beginTransaction(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     */
    @WebMethod(operationName = "CommitTransaction", action = "http://www.sones.com/GraphDS/CommitTransaction")
    @RequestWrapper(localName = "CommitTransaction", targetNamespace = "http://www.sones.com", className = "com.sones.CommitTransaction")
    @ResponseWrapper(localName = "CommitTransactionResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CommitTransactionResponse")
    public void commitTransaction(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     */
    @WebMethod(operationName = "RollbackTransaction", action = "http://www.sones.com/GraphDS/RollbackTransaction")
    @RequestWrapper(localName = "RollbackTransaction", targetNamespace = "http://www.sones.com", className = "com.sones.RollbackTransaction")
    @ResponseWrapper(localName = "RollbackTransactionResponse", targetNamespace = "http://www.sones.com", className = "com.sones.RollbackTransactionResponse")
    public void rollbackTransaction(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken);

    /**
     * 
     * @param mySecurityToken
     */
    @WebMethod(operationName = "Shutdown", action = "http://www.sones.com/GraphDS/Shutdown")
    @RequestWrapper(localName = "Shutdown", targetNamespace = "http://www.sones.com", className = "com.sones.Shutdown")
    @ResponseWrapper(localName = "ShutdownResponse", targetNamespace = "http://www.sones.com", className = "com.sones.ShutdownResponse")
    public void shutdown(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOflong
     */
    @WebMethod(operationName = "Clear", action = "http://www.sones.com/GraphDS/Clear")
    @WebResult(name = "ClearResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "Clear", targetNamespace = "http://www.sones.com", className = "com.sones.Clear")
    @ResponseWrapper(localName = "ClearResponse", targetNamespace = "http://www.sones.com", className = "com.sones.ClearResponse")
    public ArrayOflong clear(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken);

    /**
     * 
     * @param myEdgeTypePreDef
     * @param mySecurityToken
     * @param myTransactionToken
     * @return
     *     returns com.sones.ServiceEdgeType
     */
    @WebMethod(operationName = "CreateEdgeType", action = "http://www.sones.com/GraphDS/CreateEdgeType")
    @WebResult(name = "CreateEdgeTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "CreateEdgeType", targetNamespace = "http://www.sones.com", className = "com.sones.CreateEdgeType")
    @ResponseWrapper(localName = "CreateEdgeTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CreateEdgeTypeResponse")
    public ServiceEdgeType createEdgeType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myEdgeTypePreDef", targetNamespace = "http://www.sones.com")
        ServiceEdgeTypePredefinition myEdgeTypePreDef);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myVertexTypePreDef
     * @return
     *     returns com.sones.ServiceIndexDefinition
     */
    @WebMethod(operationName = "CreateIndex", action = "http://www.sones.com/GraphDS/CreateIndex")
    @WebResult(name = "CreateIndexResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "CreateIndex", targetNamespace = "http://www.sones.com", className = "com.sones.CreateIndex")
    @ResponseWrapper(localName = "CreateIndexResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CreateIndexResponse")
    public ServiceIndexDefinition createIndex(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexTypePreDef", targetNamespace = "http://www.sones.com")
        ServiceIndexPredefinition myVertexTypePreDef);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myVertexTypePreDef
     * @return
     *     returns com.sones.ArrayOfServiceVertexType
     */
    @WebMethod(operationName = "CreateVertexTypes", action = "http://www.sones.com/GraphDS/CreateVertexTypes")
    @WebResult(name = "CreateVertexTypesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "CreateVertexTypes", targetNamespace = "http://www.sones.com", className = "com.sones.CreateVertexTypes")
    @ResponseWrapper(localName = "CreateVertexTypesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CreateVertexTypesResponse")
    public ArrayOfServiceVertexType createVertexTypes(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexTypePreDef", targetNamespace = "http://www.sones.com")
        ArrayOfServiceVertexTypePredefinition myVertexTypePreDef);

    /**
     * 
     * @param myVertexType
     * @param myVertexIDs
     * @param mySecurityToken
     * @param myDeletePayload
     * @param myTransactionToken
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOflong
     */
    @WebMethod(operationName = "Delete", action = "http://www.sones.com/GraphDS/Delete")
    @WebResult(name = "DeleteResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://www.sones.com", className = "com.sones.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DeleteResponse")
    public ArrayOflong delete(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType,
        @WebParam(name = "myVertexIDs", targetNamespace = "http://www.sones.com")
        ArrayOflong myVertexIDs,
        @WebParam(name = "myDeletePayload", targetNamespace = "http://www.sones.com")
        ServiceDeletePayload myDeletePayload);

    /**
     * 
     * @param myTransToken
     * @param myVertexType
     * @param mySecurityToken
     * @param myIndexName
     * @return
     *     returns com.sones.ServiceIndexDefinition
     */
    @WebMethod(operationName = "DescribeIndex", action = "http://www.sones.com/GraphDS/DescribeIndex")
    @WebResult(name = "DescribeIndexResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "DescribeIndex", targetNamespace = "http://www.sones.com", className = "com.sones.DescribeIndex")
    @ResponseWrapper(localName = "DescribeIndexResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DescribeIndexResponse")
    public ServiceIndexDefinition describeIndex(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType,
        @WebParam(name = "myIndexName", targetNamespace = "http://www.sones.com")
        String myIndexName);

    /**
     * 
     * @param myTransToken
     * @param myVertexType
     * @param mySecurityToken
     * @return
     *     returns com.sones.ArrayOfServiceIndexDefinition
     */
    @WebMethod(operationName = "DescribeIndices", action = "http://www.sones.com/GraphDS/DescribeIndices")
    @WebResult(name = "DescribeIndicesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "DescribeIndices", targetNamespace = "http://www.sones.com", className = "com.sones.DescribeIndices")
    @ResponseWrapper(localName = "DescribeIndicesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DescribeIndicesResponse")
    public ArrayOfServiceIndexDefinition describeIndices(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myEdgeType
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOflongstring
     */
    @WebMethod(operationName = "DropEdgeType", action = "http://www.sones.com/GraphDS/DropEdgeType")
    @WebResult(name = "DropEdgeTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "DropEdgeType", targetNamespace = "http://www.sones.com", className = "com.sones.DropEdgeType")
    @ResponseWrapper(localName = "DropEdgeTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DropEdgeTypeResponse")
    public ArrayOfKeyValueOflongstring dropEdgeType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myEdgeType", targetNamespace = "http://www.sones.com")
        ServiceEdgeType myEdgeType);

    /**
     * 
     * @param myTransToken
     * @param myVertexType
     * @param mySecurityToken
     * @param myIndexName
     * @param myEdition
     */
    @WebMethod(operationName = "DropIndex", action = "http://www.sones.com/GraphDS/DropIndex")
    @RequestWrapper(localName = "DropIndex", targetNamespace = "http://www.sones.com", className = "com.sones.DropIndex")
    @ResponseWrapper(localName = "DropIndexResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DropIndexResponse")
    public void dropIndex(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType,
        @WebParam(name = "myIndexName", targetNamespace = "http://www.sones.com")
        String myIndexName,
        @WebParam(name = "myEdition", targetNamespace = "http://www.sones.com")
        String myEdition);

    /**
     * 
     * @param myTransToken
     * @param myVertexType
     * @param mySecurityToken
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOflongstring
     */
    @WebMethod(operationName = "DropVertexType", action = "http://www.sones.com/GraphDS/DropVertexType")
    @WebResult(name = "DropVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "DropVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.DropVertexType")
    @ResponseWrapper(localName = "DropVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DropVertexTypeResponse")
    public ArrayOfKeyValueOflongstring dropVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myEdition
     * @return
     *     returns com.sones.ArrayOfServiceEdgeType
     */
    @WebMethod(operationName = "GetAllEdgeTypes", action = "http://www.sones.com/GraphDS/GetAllEdgeTypes")
    @WebResult(name = "GetAllEdgeTypesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetAllEdgeTypes", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllEdgeTypes")
    @ResponseWrapper(localName = "GetAllEdgeTypesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllEdgeTypesResponse")
    public ArrayOfServiceEdgeType getAllEdgeTypes(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myEdition", targetNamespace = "http://www.sones.com")
        String myEdition);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myEdition
     * @return
     *     returns com.sones.ArrayOfServiceVertexType
     */
    @WebMethod(operationName = "GetAllVertexTypes", action = "http://www.sones.com/GraphDS/GetAllVertexTypes")
    @WebResult(name = "GetAllVertexTypesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetAllVertexTypes", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllVertexTypes")
    @ResponseWrapper(localName = "GetAllVertexTypesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllVertexTypesResponse")
    public ArrayOfServiceVertexType getAllVertexTypes(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myEdition", targetNamespace = "http://www.sones.com")
        String myEdition);

    /**
     * 
     * @param myEdgeTypeName
     * @param myTransToken
     * @param mySecurityToken
     * @param myEdition
     * @return
     *     returns com.sones.ServiceEdgeType
     */
    @WebMethod(operationName = "GetEdgeType", action = "http://www.sones.com/GraphDS/GetEdgeType")
    @WebResult(name = "GetEdgeTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetEdgeType", targetNamespace = "http://www.sones.com", className = "com.sones.GetEdgeType")
    @ResponseWrapper(localName = "GetEdgeTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetEdgeTypeResponse")
    public ServiceEdgeType getEdgeType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myEdgeTypeName", targetNamespace = "http://www.sones.com")
        String myEdgeTypeName,
        @WebParam(name = "myEdition", targetNamespace = "http://www.sones.com")
        String myEdition);

    /**
     * 
     * @param myTransToken
     * @param myVertexType
     * @param myVertexID
     * @param mySecurityToken
     * @return
     *     returns com.sones.ServiceVertexInstance
     */
    @WebMethod(operationName = "GetVertex", action = "http://www.sones.com/GraphDS/GetVertex")
    @WebResult(name = "GetVertexResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetVertex", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertex")
    @ResponseWrapper(localName = "GetVertexResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexResponse")
    public ServiceVertexInstance getVertex(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType,
        @WebParam(name = "myVertexID", targetNamespace = "http://www.sones.com")
        Long myVertexID);

    /**
     * 
     * @param myTransToken
     * @param myVertexType
     * @param mySecurityToken
     * @return
     *     returns java.math.BigInteger
     */
    @WebMethod(operationName = "GetVertexCount", action = "http://www.sones.com/GraphDS/GetVertexCount")
    @WebResult(name = "GetVertexCountResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetVertexCount", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexCount")
    @ResponseWrapper(localName = "GetVertexCountResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexCountResponse")
    public BigInteger getVertexCount(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType);

    /**
     * 
     * @param myTransToken
     * @param myVertexType
     * @param mySecurityToken
     * @return
     *     returns com.sones.ArrayOfServiceVertexInstance
     */
    @WebMethod(operationName = "GetVerticesByType", action = "http://www.sones.com/GraphDS/GetVerticesByType")
    @WebResult(name = "GetVerticesByTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetVerticesByType", targetNamespace = "http://www.sones.com", className = "com.sones.GetVerticesByType")
    @ResponseWrapper(localName = "GetVerticesByTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetVerticesByTypeResponse")
    public ArrayOfServiceVertexInstance getVerticesByType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType);

    /**
     * 
     * @param myTransToken
     * @param myVertexType
     * @param mySecurityToken
     * @return
     *     returns com.sones.ArrayOfServiceVertexInstance
     */
    @WebMethod(operationName = "GetVerticesByExpression", action = "http://www.sones.com/GraphDS/GetVerticesByExpression")
    @WebResult(name = "GetVerticesByExpressionResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetVerticesByExpression", targetNamespace = "http://www.sones.com", className = "com.sones.GetVerticesByExpression")
    @ResponseWrapper(localName = "GetVerticesByExpressionResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetVerticesByExpressionResponse")
    public ArrayOfServiceVertexInstance getVerticesByExpression(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceBaseExpression myVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myVertexTypeName
     * @param myPayload
     * @return
     *     returns com.sones.ServiceVertexInstance
     */
    @WebMethod(operationName = "Insert", action = "http://www.sones.com/GraphDS/Insert")
    @WebResult(name = "InsertResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "Insert", targetNamespace = "http://www.sones.com", className = "com.sones.Insert")
    @ResponseWrapper(localName = "InsertResponse", targetNamespace = "http://www.sones.com", className = "com.sones.InsertResponse")
    public ServiceVertexInstance insert(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexTypeName", targetNamespace = "http://www.sones.com")
        String myVertexTypeName,
        @WebParam(name = "myPayload", targetNamespace = "http://www.sones.com")
        ServiceInsertPayload myPayload);

    /**
     * 
     * @param mySecurityToken
     */
    @WebMethod(operationName = "LogOff", action = "http://www.sones.com/GraphDS/LogOff")
    @RequestWrapper(localName = "LogOff", targetNamespace = "http://www.sones.com", className = "com.sones.LogOff")
    @ResponseWrapper(localName = "LogOffResponse", targetNamespace = "http://www.sones.com", className = "com.sones.LogOffResponse")
    public void logOff(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken);

    /**
     * 
     * @param myPassword
     * @param myLogin
     * @return
     *     returns com.sones.ServiceSecurityToken
     */
    @WebMethod(operationName = "LogOn", action = "http://www.sones.com/GraphDS/LogOn")
    @WebResult(name = "LogOnResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "LogOn", targetNamespace = "http://www.sones.com", className = "com.sones.LogOn")
    @ResponseWrapper(localName = "LogOnResponse", targetNamespace = "http://www.sones.com", className = "com.sones.LogOnResponse")
    public ServiceSecurityToken logOn(
        @WebParam(name = "myLogin", targetNamespace = "http://www.sones.com")
        String myLogin,
        @WebParam(name = "myPassword", targetNamespace = "http://www.sones.com")
        String myPassword);

    /**
     * 
     * @param myTransToken
     * @param myVertexType
     * @param myUpdateChangeset
     * @param myVertexIDs
     * @param mySecurityToken
     * @return
     *     returns com.sones.ArrayOfServiceVertexInstance
     */
    @WebMethod(operationName = "Update", action = "http://www.sones.com/GraphDS/Update")
    @WebResult(name = "UpdateResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "Update", targetNamespace = "http://www.sones.com", className = "com.sones.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://www.sones.com", className = "com.sones.UpdateResponse")
    public ArrayOfServiceVertexInstance update(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType,
        @WebParam(name = "myVertexIDs", targetNamespace = "http://www.sones.com")
        ArrayOflong myVertexIDs,
        @WebParam(name = "myUpdateChangeset", targetNamespace = "http://www.sones.com")
        ServiceUpdateChangeset myUpdateChangeset);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myVertexTypeNames
     */
    @WebMethod(operationName = "RebuildIndices", action = "http://www.sones.com/GraphDS/RebuildIndices")
    @RequestWrapper(localName = "RebuildIndices", targetNamespace = "http://www.sones.com", className = "com.sones.RebuildIndices")
    @ResponseWrapper(localName = "RebuildIndicesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.RebuildIndicesResponse")
    public void rebuildIndices(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexTypeNames", targetNamespace = "http://www.sones.com")
        ArrayOfstring myVertexTypeNames);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myVertexTypeNames
     */
    @WebMethod(operationName = "TruncateVertexType", action = "http://www.sones.com/GraphDS/TruncateVertexType")
    @RequestWrapper(localName = "TruncateVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.TruncateVertexType")
    @ResponseWrapper(localName = "TruncateVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.TruncateVertexTypeResponse")
    public void truncateVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        ServiceSecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myVertexTypeNames", targetNamespace = "http://www.sones.com")
        String myVertexTypeNames);

}
