
package com.sones;

import java.math.BigInteger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOflongstring;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOflong;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import org.datacontract.schemas._2004._07.sones_library_commons.SecurityToken;
import org.datacontract.schemas._2004._07.system.TupleOfArrayOfanyTypeArrayOfanyType0DMmj3Sh;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GraphDSService", targetNamespace = "http://www.sones.com")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.sones.ObjectFactory.class,
    org.datacontract.schemas._2004._07.sones_library_commons.ObjectFactory.class,
    org.datacontract.schemas._2004._07.system.ObjectFactory.class
})
public interface GraphDSService {


    /**
     * 
     * @param mySecurityToken
     * @param myVertexTypePreDef
     * @param myTransactionToken
     * @return
     *     returns com.sones.ServiceVertexType
     */
    @WebMethod(operationName = "CreateVertexType", action = "http://www.sones.com/GraphDSService/CreateVertexType")
    @WebResult(name = "CreateVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "CreateVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.CreateVertexType")
    @ResponseWrapper(localName = "CreateVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CreateVertexTypeResponse")
    public ServiceVertexType createVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexTypePreDef", targetNamespace = "http://www.sones.com")
        ServiceVertexTypePredefinition myVertexTypePreDef);

    /**
     * 
     * @param myVertexType
     * @param mySecurityToken
     * @param myTransactionToken
     * @param myChangeset
     * @return
     *     returns com.sones.ServiceVertexType
     */
    @WebMethod(operationName = "AlterVertexType", action = "http://www.sones.com/GraphDSService/AlterVertexType")
    @WebResult(name = "AlterVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "AlterVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.AlterVertexType")
    @ResponseWrapper(localName = "AlterVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.AlterVertexTypeResponse")
    public ServiceVertexType alterVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType,
        @WebParam(name = "myChangeset", targetNamespace = "http://www.sones.com")
        ServiceAlterVertexChangeset myChangeset);

    /**
     * 
     * @param mySecurityToken
     * @param myEdgeType
     * @param myTransactionToken
     * @param myChangeset
     * @return
     *     returns com.sones.ServiceEdgeType
     */
    @WebMethod(operationName = "AlterEdgeType", action = "http://www.sones.com/GraphDSService/AlterEdgeType")
    @WebResult(name = "AlterEdgeTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "AlterEdgeType", targetNamespace = "http://www.sones.com", className = "com.sones.AlterEdgeType")
    @ResponseWrapper(localName = "AlterEdgeTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.AlterEdgeTypeResponse")
    public ServiceEdgeType alterEdgeType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myEdgeType", targetNamespace = "http://www.sones.com")
        ServiceEdgeType myEdgeType,
        @WebParam(name = "myChangeset", targetNamespace = "http://www.sones.com")
        ServiceAlterEdgeChangeset myChangeset);

    /**
     * 
     * @param mySecurityToken
     * @param myVertexTypeName
     * @param myTransactionToken
     * @return
     *     returns com.sones.ServiceVertexType
     */
    @WebMethod(operationName = "GetVertexTypeByName", action = "http://www.sones.com/GraphDSService/GetVertexTypeByName")
    @WebResult(name = "GetVertexTypeByNameResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetVertexTypeByName", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexTypeByName")
    @ResponseWrapper(localName = "GetVertexTypeByNameResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexTypeByNameResponse")
    public ServiceVertexType getVertexTypeByName(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexTypeName", targetNamespace = "http://www.sones.com")
        String myVertexTypeName);

    /**
     * 
     * @param mySecurityToken
     * @param myVertexTypeID
     * @param myTransactionToken
     * @return
     *     returns com.sones.ServiceVertexType
     */
    @WebMethod(operationName = "GetVertexTypeByID", action = "http://www.sones.com/GraphDSService/GetVertexTypeByID")
    @WebResult(name = "GetVertexTypeByIDResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetVertexTypeByID", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexTypeByID")
    @ResponseWrapper(localName = "GetVertexTypeByIDResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexTypeByIDResponse")
    public ServiceVertexType getVertexTypeByID(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexTypeID", targetNamespace = "http://www.sones.com")
        Long myVertexTypeID);

    /**
     * 
     * @param mySecurityToken
     * @return
     *     returns java.lang.Long
     */
    @WebMethod(operationName = "BeginTransaction", action = "http://www.sones.com/GraphDSService/BeginTransaction")
    @WebResult(name = "BeginTransactionResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "BeginTransaction", targetNamespace = "http://www.sones.com", className = "com.sones.BeginTransaction")
    @ResponseWrapper(localName = "BeginTransactionResponse", targetNamespace = "http://www.sones.com", className = "com.sones.BeginTransactionResponse")
    public Long beginTransaction(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken);

    /**
     * 
     * @param mySecurityToken
     * @param myTransactionToken
     */
    @WebMethod(operationName = "CommitTransaction", action = "http://www.sones.com/GraphDSService/CommitTransaction")
    @RequestWrapper(localName = "CommitTransaction", targetNamespace = "http://www.sones.com", className = "com.sones.CommitTransaction")
    @ResponseWrapper(localName = "CommitTransactionResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CommitTransactionResponse")
    public void commitTransaction(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken);

    /**
     * 
     * @param mySecurityToken
     * @param myTransactionToken
     */
    @WebMethod(operationName = "RollbackTransaction", action = "http://www.sones.com/GraphDSService/RollbackTransaction")
    @RequestWrapper(localName = "RollbackTransaction", targetNamespace = "http://www.sones.com", className = "com.sones.RollbackTransaction")
    @ResponseWrapper(localName = "RollbackTransactionResponse", targetNamespace = "http://www.sones.com", className = "com.sones.RollbackTransactionResponse")
    public void rollbackTransaction(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken);

    /**
     * 
     * @param mySecurityToken
     */
    @WebMethod(operationName = "Shutdown", action = "http://www.sones.com/GraphDSService/Shutdown")
    @RequestWrapper(localName = "Shutdown", targetNamespace = "http://www.sones.com", className = "com.sones.Shutdown")
    @ResponseWrapper(localName = "ShutdownResponse", targetNamespace = "http://www.sones.com", className = "com.sones.ShutdownResponse")
    public void shutdown(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken);

    /**
     * 
     * @param mySecurityToken
     * @param myTransactionToken
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOflong
     */
    @WebMethod(operationName = "Clear", action = "http://www.sones.com/GraphDSService/Clear")
    @WebResult(name = "ClearResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "Clear", targetNamespace = "http://www.sones.com", className = "com.sones.Clear")
    @ResponseWrapper(localName = "ClearResponse", targetNamespace = "http://www.sones.com", className = "com.sones.ClearResponse")
    public ArrayOflong clear(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken);

    /**
     * 
     * @param myEdgeTypePreDef
     * @param mySecurityToken
     * @param myTransactionToken
     * @return
     *     returns com.sones.ServiceEdgeType
     */
    @WebMethod(operationName = "CreateEdgeType", action = "http://www.sones.com/GraphDSService/CreateEdgeType")
    @WebResult(name = "CreateEdgeTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "CreateEdgeType", targetNamespace = "http://www.sones.com", className = "com.sones.CreateEdgeType")
    @ResponseWrapper(localName = "CreateEdgeTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CreateEdgeTypeResponse")
    public ServiceEdgeType createEdgeType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myEdgeTypePreDef", targetNamespace = "http://www.sones.com")
        ServiceEdgeTypePredefinition myEdgeTypePreDef);

    /**
     * 
     * @param myEdgeTypePreDef
     * @param mySecurityToken
     * @param myTransactionToken
     * @return
     *     returns com.sones.ArrayOfServiceEdgeType
     */
    @WebMethod(operationName = "CreateEdgeTypes", action = "http://www.sones.com/GraphDSService/CreateEdgeTypes")
    @WebResult(name = "CreateEdgeTypesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "CreateEdgeTypes", targetNamespace = "http://www.sones.com", className = "com.sones.CreateEdgeTypes")
    @ResponseWrapper(localName = "CreateEdgeTypesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CreateEdgeTypesResponse")
    public ArrayOfServiceEdgeType createEdgeTypes(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myEdgeTypePreDef", targetNamespace = "http://www.sones.com")
        ArrayOfServiceEdgeTypePredefinition myEdgeTypePreDef);

    /**
     * 
     * @param mySecurityToken
     * @param myVertexTypePreDef
     * @param myTransactionToken
     * @return
     *     returns com.sones.ServiceIndexDefinition
     */
    @WebMethod(operationName = "CreateIndex", action = "http://www.sones.com/GraphDSService/CreateIndex")
    @WebResult(name = "CreateIndexResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "CreateIndex", targetNamespace = "http://www.sones.com", className = "com.sones.CreateIndex")
    @ResponseWrapper(localName = "CreateIndexResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CreateIndexResponse")
    public ServiceIndexDefinition createIndex(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexTypePreDef", targetNamespace = "http://www.sones.com")
        ServiceIndexPredefinition myVertexTypePreDef);

    /**
     * 
     * @param mySecurityToken
     * @param myVertexTypePreDef
     * @param myTransactionToken
     * @return
     *     returns com.sones.ArrayOfServiceVertexType
     */
    @WebMethod(operationName = "CreateVertexTypes", action = "http://www.sones.com/GraphDSService/CreateVertexTypes")
    @WebResult(name = "CreateVertexTypesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "CreateVertexTypes", targetNamespace = "http://www.sones.com", className = "com.sones.CreateVertexTypes")
    @ResponseWrapper(localName = "CreateVertexTypesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.CreateVertexTypesResponse")
    public ArrayOfServiceVertexType createVertexTypes(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexTypePreDef", targetNamespace = "http://www.sones.com")
        ArrayOfServiceVertexTypePredefinition myVertexTypePreDef);

    /**
     * 
     * @param myVertexType
     * @param myVertexIDs
     * @param mySecurityToken
     * @param myDeletePayload
     * @param myTransactionToken
     * @return
     *     returns org.datacontract.schemas._2004._07.system.TupleOfArrayOfanyTypeArrayOfanyType0DMmj3Sh
     */
    @WebMethod(operationName = "Delete", action = "http://www.sones.com/GraphDSService/Delete")
    @WebResult(name = "DeleteResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "Delete", targetNamespace = "http://www.sones.com", className = "com.sones.Delete")
    @ResponseWrapper(localName = "DeleteResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DeleteResponse")
    public TupleOfArrayOfanyTypeArrayOfanyType0DMmj3Sh delete(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType,
        @WebParam(name = "myVertexIDs", targetNamespace = "http://www.sones.com")
        ArrayOflong myVertexIDs,
        @WebParam(name = "myDeletePayload", targetNamespace = "http://www.sones.com")
        ServiceDeletePayload myDeletePayload);

    /**
     * 
     * @param mySecurityToken
     * @param myVertexTypeName
     * @param myTransactionToken
     * @param myIndexName
     * @return
     *     returns com.sones.ServiceIndexDefinition
     */
    @WebMethod(operationName = "DescribeIndex", action = "http://www.sones.com/GraphDSService/DescribeIndex")
    @WebResult(name = "DescribeIndexResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "DescribeIndex", targetNamespace = "http://www.sones.com", className = "com.sones.DescribeIndex")
    @ResponseWrapper(localName = "DescribeIndexResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DescribeIndexResponse")
    public ServiceIndexDefinition describeIndex(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexTypeName", targetNamespace = "http://www.sones.com")
        String myVertexTypeName,
        @WebParam(name = "myIndexName", targetNamespace = "http://www.sones.com")
        String myIndexName);

    /**
     * 
     * @param mySecurityToken
     * @param myVertexTypeName
     * @param myTransactionToken
     * @return
     *     returns com.sones.ArrayOfServiceIndexDefinition
     */
    @WebMethod(operationName = "DescribeIndices", action = "http://www.sones.com/GraphDSService/DescribeIndices")
    @WebResult(name = "DescribeIndicesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "DescribeIndices", targetNamespace = "http://www.sones.com", className = "com.sones.DescribeIndices")
    @ResponseWrapper(localName = "DescribeIndicesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DescribeIndicesResponse")
    public ArrayOfServiceIndexDefinition describeIndices(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexTypeName", targetNamespace = "http://www.sones.com")
        String myVertexTypeName);

    /**
     * 
     * @param myIndexNames
     * @param mySecurityToken
     * @param myVertexTypeName
     * @param myTransactionToken
     * @return
     *     returns com.sones.ArrayOfServiceIndexDefinition
     */
    @WebMethod(operationName = "DescribeIndicesByNames", action = "http://www.sones.com/GraphDSService/DescribeIndicesByNames")
    @WebResult(name = "DescribeIndicesByNamesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "DescribeIndicesByNames", targetNamespace = "http://www.sones.com", className = "com.sones.DescribeIndicesByNames")
    @ResponseWrapper(localName = "DescribeIndicesByNamesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DescribeIndicesByNamesResponse")
    public ArrayOfServiceIndexDefinition describeIndicesByNames(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexTypeName", targetNamespace = "http://www.sones.com")
        String myVertexTypeName,
        @WebParam(name = "myIndexNames", targetNamespace = "http://www.sones.com")
        ArrayOfstring myIndexNames);

    /**
     * 
     * @param mySecurityToken
     * @param myEdgeType
     * @param myTransactionToken
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOflongstring
     */
    @WebMethod(operationName = "DropEdgeType", action = "http://www.sones.com/GraphDSService/DropEdgeType")
    @WebResult(name = "DropEdgeTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "DropEdgeType", targetNamespace = "http://www.sones.com", className = "com.sones.DropEdgeType")
    @ResponseWrapper(localName = "DropEdgeTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DropEdgeTypeResponse")
    public ArrayOfKeyValueOflongstring dropEdgeType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myEdgeType", targetNamespace = "http://www.sones.com")
        ServiceEdgeType myEdgeType);

    /**
     * 
     * @param myVertexType
     * @param mySecurityToken
     * @param myTransactionToken
     * @param myIndexName
     * @param myEdition
     */
    @WebMethod(operationName = "DropIndex", action = "http://www.sones.com/GraphDSService/DropIndex")
    @RequestWrapper(localName = "DropIndex", targetNamespace = "http://www.sones.com", className = "com.sones.DropIndex")
    @ResponseWrapper(localName = "DropIndexResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DropIndexResponse")
    public void dropIndex(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType,
        @WebParam(name = "myIndexName", targetNamespace = "http://www.sones.com")
        String myIndexName,
        @WebParam(name = "myEdition", targetNamespace = "http://www.sones.com")
        String myEdition);

    /**
     * 
     * @param myVertexType
     * @param mySecurityToken
     * @param myTransactionToken
     * @return
     *     returns com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfKeyValueOflongstring
     */
    @WebMethod(operationName = "DropVertexType", action = "http://www.sones.com/GraphDSService/DropVertexType")
    @WebResult(name = "DropVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "DropVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.DropVertexType")
    @ResponseWrapper(localName = "DropVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.DropVertexTypeResponse")
    public ArrayOfKeyValueOflongstring dropVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType);

    /**
     * 
     * @param mySecurityToken
     * @param myTransactionToken
     * @param myEdition
     * @return
     *     returns com.sones.ArrayOfServiceEdgeType
     */
    @WebMethod(operationName = "GetAllEdgeTypes", action = "http://www.sones.com/GraphDSService/GetAllEdgeTypes")
    @WebResult(name = "GetAllEdgeTypesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetAllEdgeTypes", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllEdgeTypes")
    @ResponseWrapper(localName = "GetAllEdgeTypesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllEdgeTypesResponse")
    public ArrayOfServiceEdgeType getAllEdgeTypes(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myEdition", targetNamespace = "http://www.sones.com")
        String myEdition);

    /**
     * 
     * @param mySecurityToken
     * @param myTransactionToken
     * @param myEdition
     * @return
     *     returns com.sones.ArrayOfServiceVertexType
     */
    @WebMethod(operationName = "GetAllVertexTypes", action = "http://www.sones.com/GraphDSService/GetAllVertexTypes")
    @WebResult(name = "GetAllVertexTypesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetAllVertexTypes", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllVertexTypes")
    @ResponseWrapper(localName = "GetAllVertexTypesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetAllVertexTypesResponse")
    public ArrayOfServiceVertexType getAllVertexTypes(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myEdition", targetNamespace = "http://www.sones.com")
        String myEdition);

    /**
     * 
     * @param myEdgeTypeName
     * @param mySecurityToken
     * @param myTransactionToken
     * @param myEdition
     * @return
     *     returns com.sones.ServiceEdgeType
     */
    @WebMethod(operationName = "GetEdgeTypeByName", action = "http://www.sones.com/GraphDSService/GetEdgeTypeByName")
    @WebResult(name = "GetEdgeTypeByNameResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetEdgeTypeByName", targetNamespace = "http://www.sones.com", className = "com.sones.GetEdgeTypeByName")
    @ResponseWrapper(localName = "GetEdgeTypeByNameResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetEdgeTypeByNameResponse")
    public ServiceEdgeType getEdgeTypeByName(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myEdgeTypeName", targetNamespace = "http://www.sones.com")
        String myEdgeTypeName,
        @WebParam(name = "myEdition", targetNamespace = "http://www.sones.com")
        String myEdition);

    /**
     * 
     * @param mySecurityToken
     * @param myEdgeTypeID
     * @param myTransactionToken
     * @param myEdition
     * @return
     *     returns com.sones.ServiceEdgeType
     */
    @WebMethod(operationName = "GetEdgeTypeByID", action = "http://www.sones.com/GraphDSService/GetEdgeTypeByID")
    @WebResult(name = "GetEdgeTypeByIDResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetEdgeTypeByID", targetNamespace = "http://www.sones.com", className = "com.sones.GetEdgeTypeByID")
    @ResponseWrapper(localName = "GetEdgeTypeByIDResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetEdgeTypeByIDResponse")
    public ServiceEdgeType getEdgeTypeByID(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myEdgeTypeID", targetNamespace = "http://www.sones.com")
        Long myEdgeTypeID,
        @WebParam(name = "myEdition", targetNamespace = "http://www.sones.com")
        String myEdition);

    /**
     * 
     * @param myVertexType
     * @param myVertexID
     * @param mySecurityToken
     * @param myTransactionToken
     * @return
     *     returns com.sones.ServiceVertexInstance
     */
    @WebMethod(operationName = "GetVertex", action = "http://www.sones.com/GraphDSService/GetVertex")
    @WebResult(name = "GetVertexResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetVertex", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertex")
    @ResponseWrapper(localName = "GetVertexResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexResponse")
    public ServiceVertexInstance getVertex(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType,
        @WebParam(name = "myVertexID", targetNamespace = "http://www.sones.com")
        Long myVertexID);

    /**
     * 
     * @param myVertexType
     * @param mySecurityToken
     * @param myTransactionToken
     * @return
     *     returns java.math.BigInteger
     */
    @WebMethod(operationName = "GetVertexCount", action = "http://www.sones.com/GraphDSService/GetVertexCount")
    @WebResult(name = "GetVertexCountResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetVertexCount", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexCount")
    @ResponseWrapper(localName = "GetVertexCountResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetVertexCountResponse")
    public BigInteger getVertexCount(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType);

    /**
     * 
     * @param myVertexType
     * @param mySecurityToken
     * @param myTransactionToken
     * @return
     *     returns com.sones.ArrayOfServiceVertexInstance
     */
    @WebMethod(operationName = "GetVerticesByType", action = "http://www.sones.com/GraphDSService/GetVerticesByType")
    @WebResult(name = "GetVerticesByTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetVerticesByType", targetNamespace = "http://www.sones.com", className = "com.sones.GetVerticesByType")
    @ResponseWrapper(localName = "GetVerticesByTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetVerticesByTypeResponse")
    public ArrayOfServiceVertexInstance getVerticesByType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType);

    /**
     * 
     * @param mySecurityToken
     * @param myExpression
     * @param myTransactionToken
     * @return
     *     returns com.sones.ArrayOfServiceVertexInstance
     */
    @WebMethod(operationName = "GetVerticesByExpression", action = "http://www.sones.com/GraphDSService/GetVerticesByExpression")
    @WebResult(name = "GetVerticesByExpressionResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetVerticesByExpression", targetNamespace = "http://www.sones.com", className = "com.sones.GetVerticesByExpression")
    @ResponseWrapper(localName = "GetVerticesByExpressionResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetVerticesByExpressionResponse")
    public ArrayOfServiceVertexInstance getVerticesByExpression(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myExpression", targetNamespace = "http://www.sones.com")
        ServiceBaseExpression myExpression);

    /**
     * 
     * @param mySecurityToken
     * @param myVertexTypeName
     * @param myPayload
     * @param myTransactionToken
     * @return
     *     returns com.sones.ServiceVertexInstance
     */
    @WebMethod(operationName = "Insert", action = "http://www.sones.com/GraphDSService/Insert")
    @WebResult(name = "InsertResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "Insert", targetNamespace = "http://www.sones.com", className = "com.sones.Insert")
    @ResponseWrapper(localName = "InsertResponse", targetNamespace = "http://www.sones.com", className = "com.sones.InsertResponse")
    public ServiceVertexInstance insert(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexTypeName", targetNamespace = "http://www.sones.com")
        String myVertexTypeName,
        @WebParam(name = "myPayload", targetNamespace = "http://www.sones.com")
        ServiceInsertPayload myPayload);

    /**
     * 
     * @param mySecurityToken
     */
    @WebMethod(operationName = "LogOff", action = "http://www.sones.com/GraphDSService/LogOff")
    @RequestWrapper(localName = "LogOff", targetNamespace = "http://www.sones.com", className = "com.sones.LogOff")
    @ResponseWrapper(localName = "LogOffResponse", targetNamespace = "http://www.sones.com", className = "com.sones.LogOffResponse")
    public void logOff(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken);

    /**
     * 
     * @param myUserCredentials
     * @return
     *     returns org.datacontract.schemas._2004._07.sones_library_commons.SecurityToken
     */
    @WebMethod(operationName = "LogOn", action = "http://www.sones.com/GraphDSService/LogOn")
    @WebResult(name = "LogOnResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "LogOn", targetNamespace = "http://www.sones.com", className = "com.sones.LogOn")
    @ResponseWrapper(localName = "LogOnResponse", targetNamespace = "http://www.sones.com", className = "com.sones.LogOnResponse")
    public SecurityToken logOn(
        @WebParam(name = "myUserCredentials", targetNamespace = "http://www.sones.com")
        ServiceUserPasswordCredentials myUserCredentials);

    /**
     * 
     * @param mySecToken
     * @param myLanguage
     * @param myQueryString
     * @param myTransactionToken
     * @return
     *     returns com.sones.ServiceQueryResult
     */
    @WebMethod(operationName = "Query", action = "http://www.sones.com/GraphDSService/Query")
    @WebResult(name = "QueryResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "Query", targetNamespace = "http://www.sones.com", className = "com.sones.Query")
    @ResponseWrapper(localName = "QueryResponse", targetNamespace = "http://www.sones.com", className = "com.sones.QueryResponse")
    public ServiceQueryResult query(
        @WebParam(name = "mySecToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myQueryString", targetNamespace = "http://www.sones.com")
        String myQueryString,
        @WebParam(name = "myLanguage", targetNamespace = "http://www.sones.com")
        String myLanguage);

    /**
     * 
     * @param myVertexType
     * @param myUpdateChangeset
     * @param myVertexIDs
     * @param mySecurityToken
     * @param myTransactionToken
     * @return
     *     returns com.sones.ArrayOfServiceVertexInstance
     */
    @WebMethod(operationName = "Update", action = "http://www.sones.com/GraphDSService/Update")
    @WebResult(name = "UpdateResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "Update", targetNamespace = "http://www.sones.com", className = "com.sones.Update")
    @ResponseWrapper(localName = "UpdateResponse", targetNamespace = "http://www.sones.com", className = "com.sones.UpdateResponse")
    public ArrayOfServiceVertexInstance update(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myVertexType,
        @WebParam(name = "myVertexIDs", targetNamespace = "http://www.sones.com")
        ArrayOflong myVertexIDs,
        @WebParam(name = "myUpdateChangeset", targetNamespace = "http://www.sones.com")
        ServiceUpdateChangeset myUpdateChangeset);

    /**
     * 
     * @param mySecurityToken
     * @param myVertexTypeNames
     * @param myTransactionToken
     */
    @WebMethod(operationName = "RebuildIndices", action = "http://www.sones.com/GraphDSService/RebuildIndices")
    @RequestWrapper(localName = "RebuildIndices", targetNamespace = "http://www.sones.com", className = "com.sones.RebuildIndices")
    @ResponseWrapper(localName = "RebuildIndicesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.RebuildIndicesResponse")
    public void rebuildIndices(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexTypeNames", targetNamespace = "http://www.sones.com")
        ArrayOfstring myVertexTypeNames);

    /**
     * 
     * @param mySecurityToken
     * @param myVertexTypeName
     * @param myTransactionToken
     */
    @WebMethod(operationName = "TruncateVertexType", action = "http://www.sones.com/GraphDSService/TruncateVertexType")
    @RequestWrapper(localName = "TruncateVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.TruncateVertexType")
    @ResponseWrapper(localName = "TruncateVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.TruncateVertexTypeResponse")
    public void truncateVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransactionToken", targetNamespace = "http://www.sones.com")
        Long myTransactionToken,
        @WebParam(name = "myVertexTypeName", targetNamespace = "http://www.sones.com")
        String myVertexTypeName);

}
