
package com.sones;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IRPCServiceContract", targetNamespace = "http://www.sones.com")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.sones.ObjectFactory.class,
    org.datacontract.schemas._2004._07.system.ObjectFactory.class
})
public interface IRPCServiceContract {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Ping", action = "http://www.sones.com/IRPCServiceContract/Ping")
    @WebResult(name = "PingResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "Ping", targetNamespace = "http://www.sones.com", className = "com.sones.Ping")
    @ResponseWrapper(localName = "PingResponse", targetNamespace = "http://www.sones.com", className = "com.sones.PingResponse")
    public String ping();

}
