
package com.sones;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.microsoft.schemas._2003._10.serialization.arrays.ArrayOfstring;
import org.datacontract.schemas._2004._07.sones_library_commons.SecurityToken;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.5-b04 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VertexTypeService", targetNamespace = "http://www.sones.com")
@XmlSeeAlso({
    com.microsoft.schemas._2003._10.serialization.arrays.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    com.sones.ObjectFactory.class,
    org.datacontract.schemas._2004._07.sones_library_commons.ObjectFactory.class,
    org.datacontract.schemas._2004._07.system.ObjectFactory.class
})
public interface VertexTypeService {


    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ArrayOfServiceVertexType
     */
    @WebMethod(operationName = "GetDescendantVertexTypes", action = "http://www.sones.com/VertexTypeService/GetDescendantVertexTypes")
    @WebResult(name = "GetDescendantVertexTypesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetDescendantVertexTypes", targetNamespace = "http://www.sones.com", className = "com.sones.GetDescendantVertexTypes")
    @ResponseWrapper(localName = "GetDescendantVertexTypesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetDescendantVertexTypesResponse")
    public ArrayOfServiceVertexType getDescendantVertexTypes(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ArrayOfServiceVertexType
     */
    @WebMethod(operationName = "GetDescendantVertexTypesAndSelf", action = "http://www.sones.com/VertexTypeService/GetDescendantVertexTypesAndSelf")
    @WebResult(name = "GetDescendantVertexTypesAndSelfResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetDescendantVertexTypesAndSelf", targetNamespace = "http://www.sones.com", className = "com.sones.GetDescendantVertexTypesAndSelf")
    @ResponseWrapper(localName = "GetDescendantVertexTypesAndSelfResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetDescendantVertexTypesAndSelfResponse")
    public ArrayOfServiceVertexType getDescendantVertexTypesAndSelf(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ArrayOfServiceVertexType
     */
    @WebMethod(operationName = "GetAncestorVertexTypes", action = "http://www.sones.com/VertexTypeService/GetAncestorVertexTypes")
    @WebResult(name = "GetAncestorVertexTypesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetAncestorVertexTypes", targetNamespace = "http://www.sones.com", className = "com.sones.GetAncestorVertexTypes")
    @ResponseWrapper(localName = "GetAncestorVertexTypesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetAncestorVertexTypesResponse")
    public ArrayOfServiceVertexType getAncestorVertexTypes(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ArrayOfServiceVertexType
     */
    @WebMethod(operationName = "GetAncestorVertexTypesAndSelf", action = "http://www.sones.com/VertexTypeService/GetAncestorVertexTypesAndSelf")
    @WebResult(name = "GetAncestorVertexTypesAndSelfResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetAncestorVertexTypesAndSelf", targetNamespace = "http://www.sones.com", className = "com.sones.GetAncestorVertexTypesAndSelf")
    @ResponseWrapper(localName = "GetAncestorVertexTypesAndSelfResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetAncestorVertexTypesAndSelfResponse")
    public ArrayOfServiceVertexType getAncestorVertexTypesAndSelf(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ArrayOfServiceVertexType
     */
    @WebMethod(operationName = "GetKinsmenVertexTypes", action = "http://www.sones.com/VertexTypeService/GetKinsmenVertexTypes")
    @WebResult(name = "GetKinsmenVertexTypesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetKinsmenVertexTypes", targetNamespace = "http://www.sones.com", className = "com.sones.GetKinsmenVertexTypes")
    @ResponseWrapper(localName = "GetKinsmenVertexTypesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetKinsmenVertexTypesResponse")
    public ArrayOfServiceVertexType getKinsmenVertexTypes(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ArrayOfServiceVertexType
     */
    @WebMethod(operationName = "GetKinsmenVertexTypesAndSelf", action = "http://www.sones.com/VertexTypeService/GetKinsmenVertexTypesAndSelf")
    @WebResult(name = "GetKinsmenVertexTypesAndSelfResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetKinsmenVertexTypesAndSelf", targetNamespace = "http://www.sones.com", className = "com.sones.GetKinsmenVertexTypesAndSelf")
    @ResponseWrapper(localName = "GetKinsmenVertexTypesAndSelfResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetKinsmenVertexTypesAndSelfResponse")
    public ArrayOfServiceVertexType getKinsmenVertexTypesAndSelf(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ArrayOfServiceVertexType
     */
    @WebMethod(operationName = "ChildrenVertexTypes", action = "http://www.sones.com/VertexTypeService/ChildrenVertexTypes")
    @WebResult(name = "ChildrenVertexTypesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "ChildrenVertexTypes", targetNamespace = "http://www.sones.com", className = "com.sones.ChildrenVertexTypes")
    @ResponseWrapper(localName = "ChildrenVertexTypesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.ChildrenVertexTypesResponse")
    public ArrayOfServiceVertexType childrenVertexTypes(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ServiceVertexType
     */
    @WebMethod(operationName = "ParentVertexType", action = "http://www.sones.com/VertexTypeService/ParentVertexType")
    @WebResult(name = "ParentVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "ParentVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.ParentVertexType")
    @ResponseWrapper(localName = "ParentVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.ParentVertexTypeResponse")
    public ServiceVertexType parentVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IsSealedByVertexType", action = "http://www.sones.com/VertexTypeService/IsSealedByVertexType")
    @WebResult(name = "IsSealedByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "IsSealedByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.IsSealedByVertexType")
    @ResponseWrapper(localName = "IsSealedByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.IsSealedByVertexTypeResponse")
    public Boolean isSealedByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasParentTypeByVertexType", action = "http://www.sones.com/VertexTypeService/HasParentTypeByVertexType")
    @WebResult(name = "HasParentTypeByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasParentTypeByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.HasParentTypeByVertexType")
    @ResponseWrapper(localName = "HasParentTypeByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasParentTypeByVertexTypeResponse")
    public Boolean hasParentTypeByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasChildTypeByVertexType", action = "http://www.sones.com/VertexTypeService/HasChildTypeByVertexType")
    @WebResult(name = "HasChildTypeByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasChildTypeByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.HasChildTypeByVertexType")
    @ResponseWrapper(localName = "HasChildTypeByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasChildTypeByVertexTypeResponse")
    public Boolean hasChildTypeByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType);

    /**
     * 
     * @param myOtherType
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IsAncestorByVertexType", action = "http://www.sones.com/VertexTypeService/IsAncestorByVertexType")
    @WebResult(name = "IsAncestorByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "IsAncestorByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.IsAncestorByVertexType")
    @ResponseWrapper(localName = "IsAncestorByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.IsAncestorByVertexTypeResponse")
    public Boolean isAncestorByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myOtherType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myOtherType);

    /**
     * 
     * @param myOtherType
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IsAncestorOrSelfByVertexType", action = "http://www.sones.com/VertexTypeService/IsAncestorOrSelfByVertexType")
    @WebResult(name = "IsAncestorOrSelfByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "IsAncestorOrSelfByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.IsAncestorOrSelfByVertexType")
    @ResponseWrapper(localName = "IsAncestorOrSelfByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.IsAncestorOrSelfByVertexTypeResponse")
    public Boolean isAncestorOrSelfByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myOtherType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myOtherType);

    /**
     * 
     * @param myOtherType
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IsDescendantByVertexType", action = "http://www.sones.com/VertexTypeService/IsDescendantByVertexType")
    @WebResult(name = "IsDescendantByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "IsDescendantByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.IsDescendantByVertexType")
    @ResponseWrapper(localName = "IsDescendantByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.IsDescendantByVertexTypeResponse")
    public Boolean isDescendantByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myOtherType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myOtherType);

    /**
     * 
     * @param myOtherType
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "IsDescendantOrSelfByVertexType", action = "http://www.sones.com/VertexTypeService/IsDescendantOrSelfByVertexType")
    @WebResult(name = "IsDescendantOrSelfByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "IsDescendantOrSelfByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.IsDescendantOrSelfByVertexType")
    @ResponseWrapper(localName = "IsDescendantOrSelfByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.IsDescendantOrSelfByVertexTypeResponse")
    public Boolean isDescendantOrSelfByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myOtherType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myOtherType);

    /**
     * 
     * @param myTransToken
     * @param myAttributeName
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasAttributeByVertexType", action = "http://www.sones.com/VertexTypeService/HasAttributeByVertexType")
    @WebResult(name = "HasAttributeByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasAttributeByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.HasAttributeByVertexType")
    @ResponseWrapper(localName = "HasAttributeByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasAttributeByVertexTypeResponse")
    public Boolean hasAttributeByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myAttributeName", targetNamespace = "http://www.sones.com")
        String myAttributeName);

    /**
     * 
     * @param myTransToken
     * @param myAttributeName
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ServiceAttributeDefinition
     */
    @WebMethod(operationName = "GetAttributeDefinitionByVertexType", action = "http://www.sones.com/VertexTypeService/GetAttributeDefinitionByVertexType")
    @WebResult(name = "GetAttributeDefinitionByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetAttributeDefinitionByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.GetAttributeDefinitionByVertexType")
    @ResponseWrapper(localName = "GetAttributeDefinitionByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetAttributeDefinitionByVertexTypeResponse")
    public ServiceAttributeDefinition getAttributeDefinitionByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myAttributeName", targetNamespace = "http://www.sones.com")
        String myAttributeName);

    /**
     * 
     * @param myTransToken
     * @param myAttributeID
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ServiceAttributeDefinition
     */
    @WebMethod(operationName = "GetAttributeDefinitionByIDByVertexType", action = "http://www.sones.com/VertexTypeService/GetAttributeDefinitionByIDByVertexType")
    @WebResult(name = "GetAttributeDefinitionByIDByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetAttributeDefinitionByIDByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.GetAttributeDefinitionByIDByVertexType")
    @ResponseWrapper(localName = "GetAttributeDefinitionByIDByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetAttributeDefinitionByIDByVertexTypeResponse")
    public ServiceAttributeDefinition getAttributeDefinitionByIDByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myAttributeID", targetNamespace = "http://www.sones.com")
        Long myAttributeID);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasAttributesByVertexType", action = "http://www.sones.com/VertexTypeService/HasAttributesByVertexType")
    @WebResult(name = "HasAttributesByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasAttributesByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.HasAttributesByVertexType")
    @ResponseWrapper(localName = "HasAttributesByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasAttributesByVertexTypeResponse")
    public Boolean hasAttributesByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns com.sones.ArrayOfServiceAttributeDefinition
     */
    @WebMethod(operationName = "GetAttributeDefinitionsByVertexType", action = "http://www.sones.com/VertexTypeService/GetAttributeDefinitionsByVertexType")
    @WebResult(name = "GetAttributeDefinitionsByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetAttributeDefinitionsByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.GetAttributeDefinitionsByVertexType")
    @ResponseWrapper(localName = "GetAttributeDefinitionsByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetAttributeDefinitionsByVertexTypeResponse")
    public ArrayOfServiceAttributeDefinition getAttributeDefinitionsByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

    /**
     * 
     * @param myTransToken
     * @param myAttributeName
     * @param mySecurityToken
     * @param myServiceVertexType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasPropertyByVertexType", action = "http://www.sones.com/VertexTypeService/HasPropertyByVertexType")
    @WebResult(name = "HasPropertyByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasPropertyByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.HasPropertyByVertexType")
    @ResponseWrapper(localName = "HasPropertyByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasPropertyByVertexTypeResponse")
    public Boolean hasPropertyByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myAttributeName", targetNamespace = "http://www.sones.com")
        String myAttributeName);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myPropertyName
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ServicePropertyDefinition
     */
    @WebMethod(operationName = "GetPropertyDefinitionByVertexType", action = "http://www.sones.com/VertexTypeService/GetPropertyDefinitionByVertexType")
    @WebResult(name = "GetPropertyDefinitionByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetPropertyDefinitionByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyDefinitionByVertexType")
    @ResponseWrapper(localName = "GetPropertyDefinitionByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyDefinitionByVertexTypeResponse")
    public ServicePropertyDefinition getPropertyDefinitionByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myPropertyName", targetNamespace = "http://www.sones.com")
        String myPropertyName);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myPropertyID
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ServicePropertyDefinition
     */
    @WebMethod(operationName = "GetPropertyDefinitionByIDByVertexType", action = "http://www.sones.com/VertexTypeService/GetPropertyDefinitionByIDByVertexType")
    @WebResult(name = "GetPropertyDefinitionByIDByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetPropertyDefinitionByIDByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyDefinitionByIDByVertexType")
    @ResponseWrapper(localName = "GetPropertyDefinitionByIDByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyDefinitionByIDByVertexTypeResponse")
    public ServicePropertyDefinition getPropertyDefinitionByIDByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myPropertyID", targetNamespace = "http://www.sones.com")
        Long myPropertyID);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasPropertiesByVertexType", action = "http://www.sones.com/VertexTypeService/HasPropertiesByVertexType")
    @WebResult(name = "HasPropertiesByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasPropertiesByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.HasPropertiesByVertexType")
    @ResponseWrapper(localName = "HasPropertiesByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasPropertiesByVertexTypeResponse")
    public Boolean hasPropertiesByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns com.sones.ArrayOfServicePropertyDefinition
     */
    @WebMethod(operationName = "GetPropertyDefinitionsByVertexType", action = "http://www.sones.com/VertexTypeService/GetPropertyDefinitionsByVertexType")
    @WebResult(name = "GetPropertyDefinitionsByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetPropertyDefinitionsByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyDefinitionsByVertexType")
    @ResponseWrapper(localName = "GetPropertyDefinitionsByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyDefinitionsByVertexTypeResponse")
    public ArrayOfServicePropertyDefinition getPropertyDefinitionsByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myPropertyNames
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ArrayOfServicePropertyDefinition
     */
    @WebMethod(operationName = "GetPropertyDefinitionsByNameListByVertexType", action = "http://www.sones.com/VertexTypeService/GetPropertyDefinitionsByNameListByVertexType")
    @WebResult(name = "GetPropertyDefinitionsByNameListByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetPropertyDefinitionsByNameListByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyDefinitionsByNameListByVertexType")
    @ResponseWrapper(localName = "GetPropertyDefinitionsByNameListByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetPropertyDefinitionsByNameListByVertexTypeResponse")
    public ArrayOfServicePropertyDefinition getPropertyDefinitionsByNameListByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myPropertyNames", targetNamespace = "http://www.sones.com")
        ArrayOfstring myPropertyNames);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myEdgeName
     * @param myServiceVertexType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasIncomingEdge", action = "http://www.sones.com/VertexTypeService/HasIncomingEdge")
    @WebResult(name = "HasIncomingEdgeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasIncomingEdge", targetNamespace = "http://www.sones.com", className = "com.sones.HasIncomingEdge")
    @ResponseWrapper(localName = "HasIncomingEdgeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasIncomingEdgeResponse")
    public Boolean hasIncomingEdge(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myEdgeName", targetNamespace = "http://www.sones.com")
        String myEdgeName);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myEdgeName
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ServiceIncomingEdgeDefinition
     */
    @WebMethod(operationName = "GetIncomingEdgeDefinition", action = "http://www.sones.com/VertexTypeService/GetIncomingEdgeDefinition")
    @WebResult(name = "GetIncomingEdgeDefinitionResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetIncomingEdgeDefinition", targetNamespace = "http://www.sones.com", className = "com.sones.GetIncomingEdgeDefinition")
    @ResponseWrapper(localName = "GetIncomingEdgeDefinitionResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetIncomingEdgeDefinitionResponse")
    public ServiceIncomingEdgeDefinition getIncomingEdgeDefinition(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myEdgeName", targetNamespace = "http://www.sones.com")
        String myEdgeName);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasIncomingEdges", action = "http://www.sones.com/VertexTypeService/HasIncomingEdges")
    @WebResult(name = "HasIncomingEdgesResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasIncomingEdges", targetNamespace = "http://www.sones.com", className = "com.sones.HasIncomingEdges")
    @ResponseWrapper(localName = "HasIncomingEdgesResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasIncomingEdgesResponse")
    public Boolean hasIncomingEdges(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns com.sones.ArrayOfServiceIncomingEdgeDefinition
     */
    @WebMethod(operationName = "GetIncomingEdgeDefinitions", action = "http://www.sones.com/VertexTypeService/GetIncomingEdgeDefinitions")
    @WebResult(name = "GetIncomingEdgeDefinitionsResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetIncomingEdgeDefinitions", targetNamespace = "http://www.sones.com", className = "com.sones.GetIncomingEdgeDefinitions")
    @ResponseWrapper(localName = "GetIncomingEdgeDefinitionsResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetIncomingEdgeDefinitionsResponse")
    public ArrayOfServiceIncomingEdgeDefinition getIncomingEdgeDefinitions(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myEdgeName
     * @param myServiceVertexType
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasOutgoingEdgeByVertexType", action = "http://www.sones.com/VertexTypeService/HasOutgoingEdgeByVertexType")
    @WebResult(name = "HasOutgoingEdgeByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasOutgoingEdgeByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.HasOutgoingEdgeByVertexType")
    @ResponseWrapper(localName = "HasOutgoingEdgeByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasOutgoingEdgeByVertexTypeResponse")
    public Boolean hasOutgoingEdgeByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myEdgeName", targetNamespace = "http://www.sones.com")
        String myEdgeName);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myEdgeName
     * @param myServiceVertexType
     * @return
     *     returns com.sones.ServiceOutgoingEdgeDefinition
     */
    @WebMethod(operationName = "GetOutgoingEdgeDefinitionByVertexType", action = "http://www.sones.com/VertexTypeService/GetOutgoingEdgeDefinitionByVertexType")
    @WebResult(name = "GetOutgoingEdgeDefinitionByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetOutgoingEdgeDefinitionByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.GetOutgoingEdgeDefinitionByVertexType")
    @ResponseWrapper(localName = "GetOutgoingEdgeDefinitionByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetOutgoingEdgeDefinitionByVertexTypeResponse")
    public ServiceOutgoingEdgeDefinition getOutgoingEdgeDefinitionByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myEdgeName", targetNamespace = "http://www.sones.com")
        String myEdgeName);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasOutgoingEdgesByVertexType", action = "http://www.sones.com/VertexTypeService/HasOutgoingEdgesByVertexType")
    @WebResult(name = "HasOutgoingEdgesByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasOutgoingEdgesByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.HasOutgoingEdgesByVertexType")
    @ResponseWrapper(localName = "HasOutgoingEdgesByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasOutgoingEdgesByVertexTypeResponse")
    public Boolean hasOutgoingEdgesByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns com.sones.ArrayOfServiceOutgoingEdgeDefinition
     */
    @WebMethod(operationName = "GetOutgoingEdgeDefinitionsByVertexType", action = "http://www.sones.com/VertexTypeService/GetOutgoingEdgeDefinitionsByVertexType")
    @WebResult(name = "GetOutgoingEdgeDefinitionsByVertexTypeResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetOutgoingEdgeDefinitionsByVertexType", targetNamespace = "http://www.sones.com", className = "com.sones.GetOutgoingEdgeDefinitionsByVertexType")
    @ResponseWrapper(localName = "GetOutgoingEdgeDefinitionsByVertexTypeResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetOutgoingEdgeDefinitionsByVertexTypeResponse")
    public ArrayOfServiceOutgoingEdgeDefinition getOutgoingEdgeDefinitionsByVertexType(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasUniqueDefinitions", action = "http://www.sones.com/VertexTypeService/HasUniqueDefinitions")
    @WebResult(name = "HasUniqueDefinitionsResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasUniqueDefinitions", targetNamespace = "http://www.sones.com", className = "com.sones.HasUniqueDefinitions")
    @ResponseWrapper(localName = "HasUniqueDefinitionsResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasUniqueDefinitionsResponse")
    public Boolean hasUniqueDefinitions(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns com.sones.ArrayOfServiceUniqueDefinition
     */
    @WebMethod(operationName = "GetUniqueDefinitions", action = "http://www.sones.com/VertexTypeService/GetUniqueDefinitions")
    @WebResult(name = "GetUniqueDefinitionsResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetUniqueDefinitions", targetNamespace = "http://www.sones.com", className = "com.sones.GetUniqueDefinitions")
    @ResponseWrapper(localName = "GetUniqueDefinitionsResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetUniqueDefinitionsResponse")
    public ArrayOfServiceUniqueDefinition getUniqueDefinitions(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns java.lang.Boolean
     */
    @WebMethod(operationName = "HasIndexDefinitions", action = "http://www.sones.com/VertexTypeService/HasIndexDefinitions")
    @WebResult(name = "HasIndexDefinitionsResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "HasIndexDefinitions", targetNamespace = "http://www.sones.com", className = "com.sones.HasIndexDefinitions")
    @ResponseWrapper(localName = "HasIndexDefinitionsResponse", targetNamespace = "http://www.sones.com", className = "com.sones.HasIndexDefinitionsResponse")
    public Boolean hasIndexDefinitions(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

    /**
     * 
     * @param myTransToken
     * @param mySecurityToken
     * @param myServiceVertexType
     * @param myIncludeAncestorDefinitions
     * @return
     *     returns com.sones.ArrayOfServiceIndexDefinition
     */
    @WebMethod(operationName = "GetIndexDefinitions", action = "http://www.sones.com/VertexTypeService/GetIndexDefinitions")
    @WebResult(name = "GetIndexDefinitionsResult", targetNamespace = "http://www.sones.com")
    @RequestWrapper(localName = "GetIndexDefinitions", targetNamespace = "http://www.sones.com", className = "com.sones.GetIndexDefinitions")
    @ResponseWrapper(localName = "GetIndexDefinitionsResponse", targetNamespace = "http://www.sones.com", className = "com.sones.GetIndexDefinitionsResponse")
    public ArrayOfServiceIndexDefinition getIndexDefinitions(
        @WebParam(name = "mySecurityToken", targetNamespace = "http://www.sones.com")
        SecurityToken mySecurityToken,
        @WebParam(name = "myTransToken", targetNamespace = "http://www.sones.com")
        Long myTransToken,
        @WebParam(name = "myServiceVertexType", targetNamespace = "http://www.sones.com")
        ServiceVertexType myServiceVertexType,
        @WebParam(name = "myIncludeAncestorDefinitions", targetNamespace = "http://www.sones.com")
        Boolean myIncludeAncestorDefinitions);

}
